### PR TITLE
Remove hiera data as it's unused

### PR DESCRIPTION
**Pull request by towo**
It gets automatically created when enrolling with PDK, but is entirely
unnecessary. In fact, in only results in

```
Warning: /etc/puppetlabs/code/environments/production/modules/augeas/data/common.yaml: file does not contain a valid yaml hash
```

on every Puppet run.

This PR is analogous to puppetlabs/puppetlabs-augeas_core!25, which
faced the same problem.

### CODE REVIEW

**Comment by Pigueiras** [comment]
I think this was an old problem of PDK, another option is to modify the common.yaml with (ref: https://github.com/puppetlabs/pdk-templates/pull/321/files):

```
--- {}
```

**Comment by smortex** [comment]
We can also start using it :wink: 

#84 is just the tip of the iceberg… moving from params.pp to hiera can be a good addition IMHO.

**Comment by towo** [comment]
I'd argue to merge this in now just so that there's something that isn't throwing little errors, and if needed I'll look into migrating this module to Hiera-based data. Should be possible without a major bump as AFAIR the minimum required Puppet version (4.10) supports using Hiera as a module data backend.

**Comment by raphink** [comment]
I merged #84. Thanks for this.

**Pull request closed without merging**
