### PR TITLE
Resolve puppet-lint

### PR DESCRIPTION
**Pull request by jcpunk**
This cleans up a few notices reported by `puppet-lint`

### CODE REVIEW

**Comment by raphink** [comment]
Thanks. Unfortunately, this breaks the spec tests and I don't see why.

**Comment by jcpunk** [comment]
It looks like the spec tests are using the 'legacy' facts and puppet-lint updated them to the new structured ones.

**Comment by raphink** [comment]
Yes. I had a quick look and I couldn't fix the new facts for some reason.

**Comment by jcpunk** [comment]
I've reverted the 'legacy facts' bits but left the seed values in the spec files.  In theory if I ever figure out what is wrong I'll revisit the legacy fact fixes.  But for now this PR covers most of the lint issues.... if the tests pass.

**Pull request merged**
